name: Build McBopomofo DEB

on:
  workflow_dispatch: # 讓你可以手動點擊按鈕觸發編譯

jobs:
  build_job:
    runs-on: ubuntu-24.04 # 使用最新的 Ubuntu 環境
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y pkg-config cmake extra-cmake-modules gettext \
          libfmt-dev libicu-dev libjson-c-dev libfcitx5core-dev \
          libfcitx5config-dev libfcitx5utils-dev fcitx5-modules-dev \
          checkinstall

      - name: Build and Package
        run: |
          mkdir build && cd build
          cmake ../ -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          
          # 1. 定義日期變數 (格式如 20240520)
          NOW=$(date +%Y%m%d)
          
          # 2. 將變數帶入 pkgversion
          sudo checkinstall --pkgname=fcitx5-mcbopomofo \
                            --pkgversion="1.0-$NOW" \
                            --pkgrelease="1" \
                            --type=debian \
                            --install=no \
                            --default

      - name: Upload DEB
        uses: actions/upload-artifact@v4
        with:
          # 在 Artifact 名稱也加上日期，這樣下載時的 ZIP 檔名就會帶日期
          name: mcbopomofo-package-1.0-$NOW-${{ github.run_id }} 
          path: build/*.deb
          
